inherits = "base16_default"

"ui.virtual.whitespace" = "light-gray"
"ui.virtual.indent-guide" = "light-gray"
# "ui.virtual.ruler" = "light-gray"

"ui.menu" = { fg = "black", bg = "white" }
"ui.menu.selected" = { fg = "white", bg = "gray" }
"ui.popup" = { fg = "white", bg = "gray" }
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = {}
"ui.selection" = { fg = "light-gray", bg = "gray" }
"ui.selection.primary" = { fg = "white", bg = "gray" }
# "ui.text.inactive" = { fg = "gray" }
# "ui.statusline" = { fg = "black", bg = "white" }
# "ui.statusline.inactive" = { fg = "gray", bg = "white" }
"ui.cursor" = { fg = "white", bg = "gray" } # modifiers = ["reversed"] }
# "ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"ui.help" = { fg = "white", bg = "gray" }

"attributes" = { fg = "light-yellow", modifers = ["reversed"] }
"comment" = "gray"
"constant" = "cyan"
"constant.builtin" = "yellow"
"constant.character.escape" = "yellow"
"constant.numeric" = "yellow"
"constructor" = "light-blue"
"function" = "light-blue"
"keyword" = "light-red"
"label" = { fg = "light-red" }
"namespace" = "cyan"
"operator" = "light-blue"
"special" = { fg = "light-yellow", modifers = ["reversed"] }
"string"  = "green"
"string.regexp"  = "light-magenta"
"type" = "light-blue"
"variable" = {}
"variable.builtin" = "light-magenta"
"variable.other.member" = {}

# "markup.heading" = "blue"
# "markup.list" = "red"
# "markup.bold" = { fg = "yellow", modifiers = ["bold"] }
# "markup.italic" = { fg = "magenta", modifiers = ["italic"] }
# "markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
# "markup.link.text" = "red"
# "markup.quote" = "cyan"
# "markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "light-red"

# "diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = {}
"info" = "light-blue"
# "hint" = "gray"
# "debug" = "gray"
# "warning" = "yellow"
"error" = "light-red"

