#! /bin/sh

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer  true
bspc config click_to_focus  true
bspc config pointer_follows_focus  true
bspc config pointer_follows_monitor  true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config normal_border_color "#282828"
bspc config active_border_color "#585858"
bspc config focused_border_color "#7cafc2"
